name: Trigger Read the Docs

on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'

jobs:
  trigger-rtd:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger RTD
        run: |
          curl -X POST "${{ secrets.RTD_WEBHOOK_URL }}" \
            -H "Authorization: Token ${{ secrets.RTD_TOKEN }}"